# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Projects"
  url = "#2-projects-header"
  weight = 20


[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Posts"
  url = "/all_posts"
  weight = 40

[[main]]
  name = "About"
  url = "/about_and_contact"
  weight = 50

[[main]]
  name = "Contact"
  url = "/about_and_contact/#5-contact-header"
  weight = 55

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "files/cv.pdf"
   weight = 70
